import { NextResponse } from "next/server";
import { createBriefDoc } from "@/lib/google-docs";

// Temporary diagnostic endpoint for debugging Google Doc creation.
// GET /api/test/docs → either returns the created doc URL or the full error.
// Remove this file once the Google Docs pipeline is confirmed working.
export async function GET() {
  const envCheck = {
    GOOGLE_DOCS_FOLDER_ID: process.env.GOOGLE_DOCS_FOLDER_ID ? "set" : "MISSING",
    GOOGLE_SERVICE_ACCOUNT_EMAIL: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL ?? "MISSING",
    GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: process.env.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY
      ? `set (${process.env.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY.length} chars, starts "${process.env.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY.slice(0, 30)}")`
      : "MISSING",
  };

  try {
    const url = await createBriefDoc(
      `DIAG test ${new Date().toISOString()}`,
      "Diagnostic doc generated by /api/test/docs. Safe to delete.",
    );
    return NextResponse.json({ ok: true, url, envCheck });
  } catch (err) {
    const e = err as Error & { code?: number; errors?: unknown };
    return NextResponse.json(
      {
        ok: false,
        envCheck,
        error: {
          name: e.name,
          message: e.message,
          code: e.code,
          errors: e.errors,
          stack: e.stack?.split("\n").slice(0, 8),
        },
      },
      { status: 500 },
    );
  }
}
